// Next
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Componentes
import SideNavSettings from "@/components/ui/admin/sidenavConfiguration";

export default function SettingsLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SideNavSettings>
      {/* <main className="flex-1 w-full flex flex-col overflow-hidden"> */}
      {children}
      {/* </main> */}
    </SideNavSettings>
  );
}
